---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    io.shyrka.erebus/archetype-name: "foo-sample"
    io.shyrka.erebus/archetype-version: "0.1-SNAPSHOT"
  name: myothercrd-operator
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - pods/status
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "io.github.shyrkaio.test"
  resources:
  - myothercrd
  - myothercrd/status
  verbs:
  - '*'